# Generated by Django 6.0.1 on 2026-01-23 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyprogress',
            name='study_hours',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
    ]
