# Generated by Django 6.0.1 on 2026-02-07 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0006_duel'),
    ]

    operations = [
        migrations.AddField(
            model_name='duel',
            name='creator_end_solved',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='duel',
            name='opponent_end_solved',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='duel',
            name='winner',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
