# Generated by Django 6.0.1 on 2026-01-30 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_leetcode_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_leetcode_total',
            field=models.IntegerField(default=0),
        ),
    ]
